### ISSUE TITLE
Support ARM and AArch64

### ISSUE THREAD

**Issue by Snaipe** [diacritic/BoxFort#8]

**Comment by tsieprawski** [comment]
Up. It would be cool to use boxfort (and thus criterion) on e.g. raspberry pi.

**Comment by Snaipe** [comment]
I've had reports that the ARM branch is working from a few sources, but I'm still a bit nervous about merging something that I have no means to test properly. I'm currently looking into having a proper CI process for that.

I guess I could merge it with no expectation of it working or breaking in the foreseeable future until the CI is up and running, but it's still a bit bold.

**Comment by Snaipe** [comment]
I ended up merging the code; without a proper CI in place, our best bet is hand-testing on real hardware until I find a better system. Letting working code rot would be unfortunate when people are already trying criterion on rpi.

**Comment by tiborh** [comment]
How can one test that code?
the basic system still says:
  Architecture 'armv7l' is not supported.
